### ISSUE TITLE
The font color of tooltips is always white

### ISSUE THREAD

**Issue by ryonakano** [torikulhabib/nino#11]
![Screen record from 2019-03-19 11 03 25](https://user-images.githubusercontent.com/26003928/54575248-b365e680-4a36-11e9-9656-76950b361cf9.gif)

The font color of tooltips is always white, even if you choose other color theme. This causes visibility issues because of lower contrast between the font color and the background color of tooltips.
I think we should set the font color black when the color theme is white or transparent white.

**Comment by torikulhabib** [comment]
https://github.com/torikulhabib/nino/commit/1bfbb7a0a7811a57d40496293c5da0399b066f75
