### ISSUE TITLE
I clicked the padlock item...

### ISSUE THREAD

**Issue by davewthompson** [torikulhabib/nino#2]
...and the window has vanished, and I can't get it back!

**Comment by torikulhabib** [comment]
unlock with this on terminal.

gsettings set com.github.torikulhabib.nino lock-mode unlock

I will fix soon.

**Comment by davewthompson** [comment]
I shall try that. Thank you very much

**Comment by torikulhabib** [comment]
fix https://github.com/torikulhabib/nino/commit/359f61415c8749c20512b3ff09585417ecde7460#diff-4089e5f35cbce620c0c1758fb579b361
