### ISSUE TITLE
Add appdata to be translatable

### ISSUE THREAD

**Issue by NathanBnm** [torikulhabib/nino#4]
Translating `appdata.xml` file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

**Comment by ryonakano** [comment]
It's already translatable :+1: 

e.g. 
https://github.com/torikulhabib/nino/blob/a4672f4132d33d55d43f7fc717c58a3c61f40eb0/po/com.github.torikulhabib.nino.pot#L20-L36

**Comment by NathanBnm** [comment]
@ryonakano that's true! Nevermind :+1: Closed
